/*
 * JS for BeInformed generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'b572e3eb-742e-4282-8fcc-ec2f1e9e6ff1';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "BeInformed",
    "location": "BeInformed.html"
}, {
    "name": "Screen1",
    "location": "Screen1.html"
}];

BeInformed_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilecollapsblock_219_342': 'BeInformed_mobilecollapsblock_219_342',
        'mobilecollapsblockheader_220_343': 'BeInformed_mobilecollapsblockheader_220_343',
        'mobilecollapsblockcontent_221_344': 'BeInformed_mobilecollapsblockcontent_221_344',
        'mobilelabel_222_345': 'BeInformed_mobilelabel_222_345',
        'mobilelabel_223_346': 'BeInformed_mobilelabel_223_346',
        'mobilecollapsblock_224_347': 'BeInformed_mobilecollapsblock_224_347',
        'mobilecollapsblockheader_225_348': 'BeInformed_mobilecollapsblockheader_225_348',
        'mobilecollapsblockcontent_226_349': 'BeInformed_mobilecollapsblockcontent_226_349',
        'mobilelabel_227_350': 'BeInformed_mobilelabel_227_350',
        'mobilelabel_228_351': 'BeInformed_mobilelabel_228_351',
        'mobilelabel_230_352': 'BeInformed_mobilelabel_230_352',
        'mobilelabel_233_353': 'BeInformed_mobilelabel_233_353',
        'mobilelabel_234_354': 'BeInformed_mobilelabel_234_354',
        'mobilelabel_235_355': 'BeInformed_mobilelabel_235_355',
        'mobilelabel_236_356': 'BeInformed_mobilelabel_236_356',
        'mobilecollapsblock_237_357': 'BeInformed_mobilecollapsblock_237_357',
        'mobilecollapsblockheader_238_358': 'BeInformed_mobilecollapsblockheader_238_358',
        'mobilecollapsblockcontent_239_359': 'BeInformed_mobilecollapsblockcontent_239_359',
        'mobilelabel_240_360': 'BeInformed_mobilelabel_240_360',
        'mobilelabel_241_361': 'BeInformed_mobilelabel_241_361',
        'mobilelabel_242_362': 'BeInformed_mobilelabel_242_362',
        'mobilelabel_243_363': 'BeInformed_mobilelabel_243_363',
        'mobilelabel_244_364': 'BeInformed_mobilelabel_244_364',
        'mobilelabel_245_365': 'BeInformed_mobilelabel_245_365',
        'mobilelabel_246_366': 'BeInformed_mobilelabel_246_366',
        'mobilelabel_247_367': 'BeInformed_mobilelabel_247_367',
        'mobilelabel_248_368': 'BeInformed_mobilelabel_248_368',
        'mobilelabel_249_369': 'BeInformed_mobilelabel_249_369',
        'mobilecollapsblock_250_370': 'BeInformed_mobilecollapsblock_250_370',
        'mobilecollapsblockheader_251_371': 'BeInformed_mobilecollapsblockheader_251_371',
        'mobilecollapsblockcontent_252_372': 'BeInformed_mobilecollapsblockcontent_252_372',
        'mobilelabel_253_373': 'BeInformed_mobilelabel_253_373',
        'mobilelabel_254_374': 'BeInformed_mobilelabel_254_374',
        'mobilelabel_255_375': 'BeInformed_mobilelabel_255_375',
        'mobilelabel_256_376': 'BeInformed_mobilelabel_256_376',
        'mobilelabel_257_377': 'BeInformed_mobilelabel_257_377',
        'mobilelabel_258_378': 'BeInformed_mobilelabel_258_378',
        'mobilelabel_259_379': 'BeInformed_mobilelabel_259_379',
        'mobilelabel_260_380': 'BeInformed_mobilelabel_260_380',
        'mobilecollapsblock_261': 'BeInformed_mobilecollapsblock_261',
        'mobilecollapsblockheader_262': 'BeInformed_mobilecollapsblockheader_262',
        'mobilecollapsblockcontent_263': 'BeInformed_mobilecollapsblockcontent_263',
        'mobilelabel_264': 'BeInformed_mobilelabel_264',
        'mobilecollapsblock_265': 'BeInformed_mobilecollapsblock_265',
        'mobilecollapsblockheader_266': 'BeInformed_mobilecollapsblockheader_266',
        'mobilecollapsblockcontent_267': 'BeInformed_mobilecollapsblockcontent_267',
        'mobilelabel_268': 'BeInformed_mobilelabel_268',
        'mobilelabel_269': 'BeInformed_mobilelabel_269',
        'mobilelabel_270': 'BeInformed_mobilelabel_270',
        'mobilelabel_271': 'BeInformed_mobilelabel_271',
        'mobilelabel_272': 'BeInformed_mobilelabel_272',
        'mobilelabel_273': 'BeInformed_mobilelabel_273',
        'mobilelabel_274': 'BeInformed_mobilelabel_274',
        'mobilelabel_275': 'BeInformed_mobilelabel_275',
        'mobilelabel_276': 'BeInformed_mobilelabel_276',
        'mobilelabel_277': 'BeInformed_mobilelabel_277',
        'mobilecollapsblock_278': 'BeInformed_mobilecollapsblock_278',
        'mobilecollapsblockheader_279': 'BeInformed_mobilecollapsblockheader_279',
        'mobilecollapsblockcontent_280': 'BeInformed_mobilecollapsblockcontent_280',
        'mobilelabel_281': 'BeInformed_mobilelabel_281',
        'mobilelabel_282': 'BeInformed_mobilelabel_282',
        'mobilelabel_283': 'BeInformed_mobilelabel_283',
        'mobilelabel_284': 'BeInformed_mobilelabel_284',
        'mobilelabel_285': 'BeInformed_mobilelabel_285',
        'mobilelabel_286': 'BeInformed_mobilelabel_286',
        'mobilelabel_287': 'BeInformed_mobilelabel_287',
        'mobilecollapsblock_288': 'BeInformed_mobilecollapsblock_288',
        'mobilecollapsblockheader_289': 'BeInformed_mobilecollapsblockheader_289',
        'mobilecollapsblockcontent_290': 'BeInformed_mobilecollapsblockcontent_290',
        'mobilelabel_291': 'BeInformed_mobilelabel_291',
        'mobilelabel_292': 'BeInformed_mobilelabel_292',
        'mobilelabel_293': 'BeInformed_mobilelabel_293',
        'mobilelabel_294': 'BeInformed_mobilelabel_294',
        'mobilelabel_295': 'BeInformed_mobilelabel_295',
        'mobilelabel_296': 'BeInformed_mobilelabel_296',
        'mobilelabel_297': 'BeInformed_mobilelabel_297',
        'mobilelabel_298': 'BeInformed_mobilelabel_298',
        'mobilelabel_299': 'BeInformed_mobilelabel_299',
        'mobilelabel_300': 'BeInformed_mobilelabel_300',
        'mobilelabel_301': 'BeInformed_mobilelabel_301',
        'mobilelabel_302': 'BeInformed_mobilelabel_302',
        'mobilelabel_303': 'BeInformed_mobilelabel_303',
        'mobilecollapsblock_304': 'BeInformed_mobilecollapsblock_304',
        'mobilecollapsblockheader_305': 'BeInformed_mobilecollapsblockheader_305',
        'mobilecollapsblockcontent_306': 'BeInformed_mobilecollapsblockcontent_306',
        'mobilelabel_307': 'BeInformed_mobilelabel_307',
        'mobilecollapsblock_308': 'BeInformed_mobilecollapsblock_308',
        'mobilecollapsblockheader_309': 'BeInformed_mobilecollapsblockheader_309',
        'mobilecollapsblockcontent_310': 'BeInformed_mobilecollapsblockcontent_310',
        'mobilelabel_311': 'BeInformed_mobilelabel_311',
        'mobilelabel_312': 'BeInformed_mobilelabel_312',
        'mobilelabel_313': 'BeInformed_mobilelabel_313',
        'mobilelabel_314': 'BeInformed_mobilelabel_314',
        'mobilelabel_315': 'BeInformed_mobilelabel_315',
        'mobilelabel_316': 'BeInformed_mobilelabel_316',
        'mobilelabel_317': 'BeInformed_mobilelabel_317',
        'mobilelabel_318': 'BeInformed_mobilelabel_318',
        'mobilecollapsblock_319': 'BeInformed_mobilecollapsblock_319',
        'mobilecollapsblockheader_320': 'BeInformed_mobilecollapsblockheader_320',
        'mobilecollapsblockcontent_321': 'BeInformed_mobilecollapsblockcontent_321',
        'mobilelabel_322': 'BeInformed_mobilelabel_322',
        'mobilelabel_323': 'BeInformed_mobilelabel_323',
        'mobilelabel_324': 'BeInformed_mobilelabel_324',
        'mobilelabel_325': 'BeInformed_mobilelabel_325',
        'mobilelabel_326': 'BeInformed_mobilelabel_326',
        'mobilelabel_327': 'BeInformed_mobilelabel_327',
        'mobilelabel_328': 'BeInformed_mobilelabel_328',
        'mobilecollapsblock_329': 'BeInformed_mobilecollapsblock_329',
        'mobilecollapsblockheader_330': 'BeInformed_mobilecollapsblockheader_330',
        'mobilecollapsblockcontent_331': 'BeInformed_mobilecollapsblockcontent_331',
        'mobilelabel_332': 'BeInformed_mobilelabel_332',
        'mobilelabel_333': 'BeInformed_mobilelabel_333',
        'mobilelabel_334': 'BeInformed_mobilelabel_334',
        'mobilelabel_335': 'BeInformed_mobilelabel_335',
        'mobilelabel_336': 'BeInformed_mobilelabel_336',
        'mobilelabel_337': 'BeInformed_mobilelabel_337',
        'mobilelabel_338': 'BeInformed_mobilelabel_338',
        'mobilelabel_339': 'BeInformed_mobilelabel_339',
        'mobilelabel_340': 'BeInformed_mobilelabel_340',
        'mobilecollapsblock_384': 'BeInformed_mobilecollapsblock_384',
        'mobilecollapsblockheader_385': 'BeInformed_mobilecollapsblockheader_385',
        'mobilecollapsblockcontent_386': 'BeInformed_mobilecollapsblockcontent_386',
        'mobilelabel_387': 'BeInformed_mobilelabel_387',
        'mobilelabel_388': 'BeInformed_mobilelabel_388',
        'mobilecollapsblock_389': 'BeInformed_mobilecollapsblock_389',
        'mobilecollapsblockheader_390': 'BeInformed_mobilecollapsblockheader_390',
        'mobilecollapsblockcontent_391': 'BeInformed_mobilecollapsblockcontent_391',
        'mobilelabel_392': 'BeInformed_mobilelabel_392',
        'mobilelabel_393': 'BeInformed_mobilelabel_393',
        'mobilelabel_394': 'BeInformed_mobilelabel_394',
        'mobilelabel_395': 'BeInformed_mobilelabel_395',
        'mobilelabel_396': 'BeInformed_mobilelabel_396',
        'mobilecollapsblock_397': 'BeInformed_mobilecollapsblock_397',
        'mobilecollapsblockheader_398': 'BeInformed_mobilecollapsblockheader_398',
        'mobilecollapsblockcontent_399': 'BeInformed_mobilecollapsblockcontent_399',
        'mobilelabel_400': 'BeInformed_mobilelabel_400',
        'mobilelabel_401': 'BeInformed_mobilelabel_401',
        'mobilelabel_402': 'BeInformed_mobilelabel_402',
        'mobilelabel_403': 'BeInformed_mobilelabel_403',
        'mobilelabel_404': 'BeInformed_mobilelabel_404',
        'mobilecollapsblock_405': 'BeInformed_mobilecollapsblock_405',
        'mobilecollapsblockheader_406': 'BeInformed_mobilecollapsblockheader_406',
        'mobilecollapsblockcontent_407': 'BeInformed_mobilecollapsblockcontent_407',
        'mobilelabel_408': 'BeInformed_mobilelabel_408',
        'mobilelabel_409': 'BeInformed_mobilelabel_409',
        'mobilelabel_410': 'BeInformed_mobilelabel_410',
        'mobilelabel_411': 'BeInformed_mobilelabel_411',
        'mobilelabel_412': 'BeInformed_mobilelabel_412',
        'mobilelabel_413': 'BeInformed_mobilelabel_413',
        'mobilecollapsblock_414': 'BeInformed_mobilecollapsblock_414',
        'mobilecollapsblockheader_415': 'BeInformed_mobilecollapsblockheader_415',
        'mobilecollapsblockcontent_416': 'BeInformed_mobilecollapsblockcontent_416',
        'mobilelabel_417': 'BeInformed_mobilelabel_417',
        'mobilecollapsblock_418': 'BeInformed_mobilecollapsblock_418',
        'mobilecollapsblockheader_419': 'BeInformed_mobilecollapsblockheader_419',
        'mobilecollapsblockcontent_420': 'BeInformed_mobilecollapsblockcontent_420',
        'mobilelabel_421': 'BeInformed_mobilelabel_421',
        'mobilelabel_422': 'BeInformed_mobilelabel_422',
        'mobilelabel_423': 'BeInformed_mobilelabel_423',
        'mobilecollapsblock_424': 'BeInformed_mobilecollapsblock_424',
        'mobilecollapsblockheader_425': 'BeInformed_mobilecollapsblockheader_425',
        'mobilecollapsblockcontent_426': 'BeInformed_mobilecollapsblockcontent_426',
        'mobilelabel_427': 'BeInformed_mobilelabel_427',
        'mobilelabel_428': 'BeInformed_mobilelabel_428',
        'mobilelabel_429': 'BeInformed_mobilelabel_429',
        'mobilelabel_430': 'BeInformed_mobilelabel_430',
        'mobilecollapsblock_431': 'BeInformed_mobilecollapsblock_431',
        'mobilecollapsblockheader_432': 'BeInformed_mobilecollapsblockheader_432',
        'mobilecollapsblockcontent_433': 'BeInformed_mobilecollapsblockcontent_433',
        'mobilelabel_434': 'BeInformed_mobilelabel_434',
        'mobilelabel_435': 'BeInformed_mobilelabel_435',
        'mobilecollapsblock_436': 'BeInformed_mobilecollapsblock_436',
        'mobilecollapsblockheader_437': 'BeInformed_mobilecollapsblockheader_437',
        'mobilecollapsblockcontent_438': 'BeInformed_mobilecollapsblockcontent_438',
        'mobilelabel_439': 'BeInformed_mobilelabel_439',
        'mobilecollapsblock_440': 'BeInformed_mobilecollapsblock_440',
        'mobilecollapsblockheader_441': 'BeInformed_mobilecollapsblockheader_441',
        'mobilecollapsblockcontent_442': 'BeInformed_mobilecollapsblockcontent_442',
        'mobilelabel_443': 'BeInformed_mobilelabel_443',
        'mobilelabel_444': 'BeInformed_mobilelabel_444',
        'mobilelabel_445': 'BeInformed_mobilelabel_445',
        'mobilelabel_446': 'BeInformed_mobilelabel_446',
        'mobilelabel_447': 'BeInformed_mobilelabel_447',
        'mobilelabel_448': 'BeInformed_mobilelabel_448',
        'mobilecollapsblock_449': 'BeInformed_mobilecollapsblock_449',
        'mobilecollapsblockheader_450': 'BeInformed_mobilecollapsblockheader_450',
        'mobilecollapsblockcontent_451': 'BeInformed_mobilecollapsblockcontent_451',
        'mobilelabel_452': 'BeInformed_mobilelabel_452',
        'mobilelabel_453': 'BeInformed_mobilelabel_453',
        'mobilelabel_454': 'BeInformed_mobilelabel_454',
        'mobilelabel_455': 'BeInformed_mobilelabel_455',
        'mobilelabel_456': 'BeInformed_mobilelabel_456',
        'mobilelabel_457': 'BeInformed_mobilelabel_457',
        'mobilecollapsblock_461': 'BeInformed_mobilecollapsblock_461',
        'mobilecollapsblockheader_462': 'BeInformed_mobilecollapsblockheader_462',
        'mobilecollapsblockcontent_463': 'BeInformed_mobilecollapsblockcontent_463',
        'mobilelabel_464': 'BeInformed_mobilelabel_464',
        'mobilelabel_465': 'BeInformed_mobilelabel_465',
        'mobilelabel_466': 'BeInformed_mobilelabel_466',
        'mobilelabel_467': 'BeInformed_mobilelabel_467',
        'mobilelabel_469': 'BeInformed_mobilelabel_469',
        'mobilelabel_468': 'BeInformed_mobilelabel_468'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fix for jQuery Mobile's footer in Cordova webview on WP8 devices
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
        document.createTextNode("@media screen and (orientation: portrait){@-ms-viewport {width: 320px; height: 534px;user-zoom: fixed;zoom: 1;}}" + "@media screen and (orientation:landscape){@-ms-viewport{width:480px;user-zoom:fixed;zoom:1;}}"));
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    Apperyio.CurrentScreen = 'BeInformed';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    var BeInformed_beforeshow = function() {
            Apperyio.CurrentScreen = "BeInformed";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var BeInformed_onLoad = function() {
            BeInformed_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            BeInformed_deviceEvents();
            BeInformed_windowEvents();
            BeInformed_elementsEvents();
        };

    // screen window events
    var BeInformed_windowEvents = function() {

            $('#BeInformed').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var BeInformed_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var BeInformed_elementsExtraJS = function() {
            // screen (BeInformed) extra code

            /* mobilecollapsblock_219_342 */

            $("#BeInformed_mobilecollapsblock_219_342 .ui-collapsible-heading-toggle").attr("tabindex", "16");

            /* mobilecollapsblock_224_347 */

            $("#BeInformed_mobilecollapsblock_224_347 .ui-collapsible-heading-toggle").attr("tabindex", "17");

            /* mobilecollapsblock_237_357 */

            $("#BeInformed_mobilecollapsblock_237_357 .ui-collapsible-heading-toggle").attr("tabindex", "18");

            /* mobilecollapsblock_250_370 */

            $("#BeInformed_mobilecollapsblock_250_370 .ui-collapsible-heading-toggle").attr("tabindex", "19");

            /* mobilecollapsblock_261 */

            $("#BeInformed_mobilecollapsblock_261 .ui-collapsible-heading-toggle").attr("tabindex", "20");

            /* mobilecollapsblock_265 */

            $("#BeInformed_mobilecollapsblock_265 .ui-collapsible-heading-toggle").attr("tabindex", "21");

            /* mobilecollapsblock_278 */

            $("#BeInformed_mobilecollapsblock_278 .ui-collapsible-heading-toggle").attr("tabindex", "22");

            /* mobilecollapsblock_288 */

            $("#BeInformed_mobilecollapsblock_288 .ui-collapsible-heading-toggle").attr("tabindex", "23");

            /* mobilecollapsblock_304 */

            $("#BeInformed_mobilecollapsblock_304 .ui-collapsible-heading-toggle").attr("tabindex", "24");

            /* mobilecollapsblock_308 */

            $("#BeInformed_mobilecollapsblock_308 .ui-collapsible-heading-toggle").attr("tabindex", "25");

            /* mobilecollapsblock_319 */

            $("#BeInformed_mobilecollapsblock_319 .ui-collapsible-heading-toggle").attr("tabindex", "26");

            /* mobilecollapsblock_329 */

            $("#BeInformed_mobilecollapsblock_329 .ui-collapsible-heading-toggle").attr("tabindex", "27");

            /* mobilecollapsblock_384 */

            $("#BeInformed_mobilecollapsblock_384 .ui-collapsible-heading-toggle").attr("tabindex", "29");

            /* mobilecollapsblock_389 */

            $("#BeInformed_mobilecollapsblock_389 .ui-collapsible-heading-toggle").attr("tabindex", "30");

            /* mobilecollapsblock_397 */

            $("#BeInformed_mobilecollapsblock_397 .ui-collapsible-heading-toggle").attr("tabindex", "31");

            /* mobilecollapsblock_405 */

            $("#BeInformed_mobilecollapsblock_405 .ui-collapsible-heading-toggle").attr("tabindex", "32");

            /* mobilecollapsblock_414 */

            $("#BeInformed_mobilecollapsblock_414 .ui-collapsible-heading-toggle").attr("tabindex", "33");

            /* mobilecollapsblock_418 */

            $("#BeInformed_mobilecollapsblock_418 .ui-collapsible-heading-toggle").attr("tabindex", "34");

            /* mobilecollapsblock_424 */

            $("#BeInformed_mobilecollapsblock_424 .ui-collapsible-heading-toggle").attr("tabindex", "35");

            /* mobilecollapsblock_431 */

            $("#BeInformed_mobilecollapsblock_431 .ui-collapsible-heading-toggle").attr("tabindex", "36");

            /* mobilecollapsblock_436 */

            $("#BeInformed_mobilecollapsblock_436 .ui-collapsible-heading-toggle").attr("tabindex", "37");

            /* mobilecollapsblock_440 */

            $("#BeInformed_mobilecollapsblock_440 .ui-collapsible-heading-toggle").attr("tabindex", "38");

            /* mobilecollapsblock_449 */

            $("#BeInformed_mobilecollapsblock_449 .ui-collapsible-heading-toggle").attr("tabindex", "39");

            /* mobilecollapsblock_461 */

            $("#BeInformed_mobilecollapsblock_461 .ui-collapsible-heading-toggle").attr("tabindex", "41");

        };

    // screen elements handler
    var BeInformed_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

        };

    $(document).off("pagebeforeshow", "#BeInformed").on("pagebeforeshow", "#BeInformed", function(event, ui) {
        BeInformed_beforeshow();
    });

    if (runBeforeShow) {
        BeInformed_beforeshow();
    } else {
        BeInformed_onLoad();
    }
};

$(document).off("pagecreate", "#BeInformed").on("pagecreate", "#BeInformed", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    BeInformed_js();
});