/*
 * JS for Screen1 generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'b572e3eb-742e-4282-8fcc-ec2f1e9e6ff1';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "BeInformed",
    "location": "BeInformed.html"
}, {
    "name": "Screen1",
    "location": "Screen1.html"
}];

Screen1_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_2': 'Screen1_mobilelabel_2',
        'mobilecheckboxgroup_3': 'Screen1_mobilecheckboxgroup_3',
        'mobilecheckbox_4': 'Screen1_mobilecheckbox_4',
        'mobilecheckbox_5': 'Screen1_mobilecheckbox_5',
        'mobilecheckbox_6': 'Screen1_mobilecheckbox_6',
        'mobilecheckboxgroup_7': 'Screen1_mobilecheckboxgroup_7',
        'mobilecheckbox_8': 'Screen1_mobilecheckbox_8',
        'mobilecheckbox_9': 'Screen1_mobilecheckbox_9',
        'mobilecheckbox_10': 'Screen1_mobilecheckbox_10',
        'mobilecollapsblock_11': 'Screen1_mobilecollapsblock_11',
        'mobilecollapsblockheader_12': 'Screen1_mobilecollapsblockheader_12',
        'mobilecollapsblockcontent_13': 'Screen1_mobilecollapsblockcontent_13',
        'mobilelabel_14': 'Screen1_mobilelabel_14',
        'mobilecollapsibleset_18': 'Screen1_mobilecollapsibleset_18',
        'mobilecollapsblock_19': 'Screen1_mobilecollapsblock_19',
        'mobilecollapsblockheader_20': 'Screen1_mobilecollapsblockheader_20',
        'mobilecollapsblockcontent_21': 'Screen1_mobilecollapsblockcontent_21',
        'mobiletextinput_29': 'Screen1_mobiletextinput_29'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fix for jQuery Mobile's footer in Cordova webview on WP8 devices
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
        document.createTextNode("@media screen and (orientation: portrait){@-ms-viewport {width: 320px; height: 534px;user-zoom: fixed;zoom: 1;}}" + "@media screen and (orientation:landscape){@-ms-viewport{width:480px;user-zoom:fixed;zoom:1;}}"));
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    Apperyio.CurrentScreen = 'Screen1';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    var Screen1_beforeshow = function() {
            Apperyio.CurrentScreen = "Screen1";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var Screen1_onLoad = function() {
            Screen1_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            Screen1_deviceEvents();
            Screen1_windowEvents();
            Screen1_elementsEvents();
        };

    // screen window events
    var Screen1_windowEvents = function() {

            $('#Screen1').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var Screen1_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var Screen1_elementsExtraJS = function() {
            // screen (Screen1) extra code

            /* mobilecollapsblock_11 */

            $("#Screen1_mobilecollapsblock_11 .ui-collapsible-heading-toggle").attr("tabindex", "3");

            /* mobilecollapsblock_19 */

            $("#Screen1_mobilecollapsblock_19 .ui-collapsible-heading-toggle").attr("tabindex", "5");

        };

    // screen elements handler
    var Screen1_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

        };

    $(document).off("pagebeforeshow", "#Screen1").on("pagebeforeshow", "#Screen1", function(event, ui) {
        Screen1_beforeshow();
    });

    if (runBeforeShow) {
        Screen1_beforeshow();
    } else {
        Screen1_onLoad();
    }
};

$(document).off("pagecreate", "#Screen1").on("pagecreate", "#Screen1", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Screen1_js();
});