/*
 * JS for startScreen generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'b572e3eb-742e-4282-8fcc-ec2f1e9e6ff1';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "BeInformed",
    "location": "BeInformed.html"
}, {
    "name": "Screen1",
    "location": "Screen1.html"
}];

startScreen_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilecollapsblock_3': 'startScreen_mobilecollapsblock_3',
        'mobilecollapsblockheader_4': 'startScreen_mobilecollapsblockheader_4',
        'mobilecollapsblockcontent_5': 'startScreen_mobilecollapsblockcontent_5',
        'mobilelist_25': 'startScreen_mobilelist_25',
        'mobilelistitem_26': 'startScreen_mobilelistitem_26',
        'mobilelistitembutton_27': 'startScreen_mobilelistitembutton_27',
        'mobilelistitem_28': 'startScreen_mobilelistitem_28',
        'mobilelistitembutton_29': 'startScreen_mobilelistitembutton_29',
        'mobilecollapsblock_56': 'startScreen_mobilecollapsblock_56',
        'mobilecollapsblockheader_57': 'startScreen_mobilecollapsblockheader_57',
        'mobilecollapsblockcontent_58': 'startScreen_mobilecollapsblockcontent_58',
        'mobilecollapsibleset_126': 'startScreen_mobilecollapsibleset_126',
        'mobilecollapsblock_127': 'startScreen_mobilecollapsblock_127',
        'mobilecollapsblockheader_128': 'startScreen_mobilecollapsblockheader_128',
        'mobilecollapsblockcontent_129': 'startScreen_mobilecollapsblockcontent_129',
        'mobilelabel_136': 'startScreen_mobilelabel_136',
        'mobilelabel_137': 'startScreen_mobilelabel_137',
        'mobilelabel_138': 'startScreen_mobilelabel_138',
        'mobilelabel_139': 'startScreen_mobilelabel_139',
        'mobilelabel_140': 'startScreen_mobilelabel_140',
        'mobilelabel_141': 'startScreen_mobilelabel_141',
        'mobilelabel_142': 'startScreen_mobilelabel_142',
        'mobilelabel_143': 'startScreen_mobilelabel_143',
        'mobilelabel_144': 'startScreen_mobilelabel_144',
        'mobilelabel_145': 'startScreen_mobilelabel_145',
        'mobilelabel_146': 'startScreen_mobilelabel_146',
        'mobilelabel_147': 'startScreen_mobilelabel_147',
        'mobilelabel_148': 'startScreen_mobilelabel_148',
        'mobilelabel_149': 'startScreen_mobilelabel_149',
        'mobilelabel_150': 'startScreen_mobilelabel_150',
        'mobilelabel_151': 'startScreen_mobilelabel_151',
        'mobilelabel_152': 'startScreen_mobilelabel_152',
        'mobilelabel_153': 'startScreen_mobilelabel_153',
        'mobilelabel_154': 'startScreen_mobilelabel_154',
        'mobilelabel_155': 'startScreen_mobilelabel_155',
        'mobilelabel_156': 'startScreen_mobilelabel_156',
        'mobilelabel_157': 'startScreen_mobilelabel_157',
        'mobilecollapsblock_133': 'startScreen_mobilecollapsblock_133',
        'mobilecollapsblockheader_134': 'startScreen_mobilecollapsblockheader_134',
        'mobilecollapsblockcontent_135': 'startScreen_mobilecollapsblockcontent_135',
        'mobilelabel_158': 'startScreen_mobilelabel_158',
        'mobilelabel_159': 'startScreen_mobilelabel_159',
        'mobilelabel_160': 'startScreen_mobilelabel_160',
        'mobilelabel_161': 'startScreen_mobilelabel_161',
        'mobilelabel_162': 'startScreen_mobilelabel_162',
        'mobilelabel_163': 'startScreen_mobilelabel_163',
        'mobilelabel_164': 'startScreen_mobilelabel_164',
        'mobilecollapsblock_37': 'startScreen_mobilecollapsblock_37',
        'mobilecollapsblockheader_38': 'startScreen_mobilecollapsblockheader_38',
        'mobilecollapsblockcontent_39': 'startScreen_mobilecollapsblockcontent_39',
        'mobilelabel_40': 'startScreen_mobilelabel_40',
        'mobilelabel_42': 'startScreen_mobilelabel_42',
        'mobilelabel_43': 'startScreen_mobilelabel_43',
        'mobilelabel_44': 'startScreen_mobilelabel_44'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fix for jQuery Mobile's footer in Cordova webview on WP8 devices
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
        document.createTextNode("@media screen and (orientation: portrait){@-ms-viewport {width: 320px; height: 534px;user-zoom: fixed;zoom: 1;}}" + "@media screen and (orientation:landscape){@-ms-viewport{width:480px;user-zoom:fixed;zoom:1;}}"));
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    Apperyio.CurrentScreen = 'startScreen';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    var startScreen_beforeshow = function() {
            Apperyio.CurrentScreen = "startScreen";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var startScreen_onLoad = function() {
            startScreen_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            startScreen_deviceEvents();
            startScreen_windowEvents();
            startScreen_elementsEvents();
        };

    // screen window events
    var startScreen_windowEvents = function() {

            $('#startScreen').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var startScreen_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var startScreen_elementsExtraJS = function() {
            // screen (startScreen) extra code

            /* mobilecollapsblock_3 */

            $("#startScreen_mobilecollapsblock_3 .ui-collapsible-heading-toggle").attr("tabindex", "2");

            /* mobilelist_25 */

            listView = $("#startScreen_mobilelist_25");
            theme = listView.attr("data-theme");
            if (typeof theme !== 'undefined') {
                var themeClass = "ui-btn-up-" + theme;
                listItem = $("#startScreen_mobilelist_25 .ui-li-static");
                $.each(listItem, function(index, value) {
                    $(this).addClass(themeClass);
                });
            }

            /* mobilelistitem_26 */

            /* mobilelistitem_28 */

            /* mobilecollapsblock_56 */

            $("#startScreen_mobilecollapsblock_56 .ui-collapsible-heading-toggle").attr("tabindex", "15");

            /* mobilecollapsblock_127 */

            $("#startScreen_mobilecollapsblock_127 .ui-collapsible-heading-toggle").attr("tabindex", "20");

            /* mobilecollapsblock_133 */

            $("#startScreen_mobilecollapsblock_133 .ui-collapsible-heading-toggle").attr("tabindex", "20");

            /* mobilecollapsblock_37 */

            $("#startScreen_mobilecollapsblock_37 .ui-collapsible-heading-toggle").attr("tabindex", "13");

        };

    // screen elements handler
    var startScreen_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click", '#startScreen_mobilecontainer1 [name="mobilelistitem_26"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Apperyio.navigateTo('BeInformed', {
                            reverse: false
                        });

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="mobilelistitem_26"]');

            $(document).off("click", '#startScreen_mobilecontainer1 [name="mobilelistitem_28"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Apperyio.navigateTo('Screen1', {
                            reverse: false
                        });

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="mobilelistitem_28"]');

        };

    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        startScreen_beforeshow();
    });

    if (runBeforeShow) {
        startScreen_beforeshow();
    } else {
        startScreen_onLoad();
    }
};

$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_js();
});